<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Aravind" failures="5" tests="16" name="Default test" time="371.182" errors="0" timestamp="02 May 2024 13:37:50 GMT">
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="preSetup" time="9.015"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_73_To_Validate_the_presence_of_placeholder_in_the_Create_password_Fields" time="1.414"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_60_To_Validate_the_next_function_without_entering_a_value_in_Enter_password_and_ReEnter_password" time="3.156"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_57_To_Validate_with_Valid_value_in_enter_password_field_and_Invalid_value_in_ReEnter_password_field" time="19.338"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_61_To_Validate_the_next_function_without_entering_a_value_in_Enter_password_and_with_a_value_in_ReEnter_password" time="17.009"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_62_To_Validate_the_next_function_with_value_only_In_ReEnter_password_Field" time="27.952"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_65_To_Validate_the_Pin_number_fields_by_entering_values_below_boundary_value_In_both_Fields" time="34.868"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_66_To_Validate_the_Password_number_fields_by_entering_values_below_boundary_value_in_any_one_field" time="43.043"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_76_And_77_To_validate_Whether_Values_In_Password_Fields_are_Editable_And_deletable" time="55.675"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values" time="15.614">
    <failure type="java.lang.AssertionError" message="Not able to Paste values other than numbers expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Not able to Paste values other than numbers expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities.TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values(CreatePasswrod_Screen_And_its_Functionalities.java:251)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values -->
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values" time="21.329">
    <failure type="java.lang.AssertionError" message="Not able to Paste values other than numbers expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Not able to Paste values other than numbers expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities.TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values(CreatePasswrod_Screen_And_its_Functionalities.java:251)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values -->
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values" time="23.629">
    <failure type="java.lang.AssertionError" message="Not able to Paste values other than numbers expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Not able to Paste values other than numbers expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities.TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values(CreatePasswrod_Screen_And_its_Functionalities.java:251)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_To_Validate_Working_of_Paste_Option_With_different_InValid_values -->
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_71_To_Validate_Create_password_by_pasting_numerical_value" time="15.169"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_58_To_Validate_with_Valid_value_in_both_enter_password_field_and_in_ReEnter_password_field" time="43.442"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_72_Validate_whether_crusher_blink_on_clicking_the_Create_password" time="0.344">
    <failure type="java.lang.AssertionError" message="expected [Create Password] but found [Recovery Phrase]">
      <![CDATA[java.lang.AssertionError: expected [Create Password] but found [Recovery Phrase]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities.TC_72_Validate_whether_crusher_blink_on_clicking_the_Create_password(CreatePasswrod_Screen_And_its_Functionalities.java:324)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_72_Validate_whether_crusher_blink_on_clicking_the_Create_password -->
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_66_Validate_the_Create_password_by_entering_values_above_boundary_value_And_Is_able_To_copy" time="0.364">
    <failure type="java.lang.AssertionError" message="expected [Create Password] but found [Recovery Phrase]">
      <![CDATA[java.lang.AssertionError: expected [Create Password] but found [Recovery Phrase]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities.TC_66_Validate_the_Create_password_by_entering_values_above_boundary_value_And_Is_able_To_copy(CreatePasswrod_Screen_And_its_Functionalities.java:347)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_66_Validate_the_Create_password_by_entering_values_above_boundary_value_And_Is_able_To_copy -->
</testsuite> <!-- Default test -->
