<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Aravind" failures="1" tests="5" name="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" time="68.814" errors="0" timestamp="26 Apr 2024 11:26:04 GMT" skipped="0">
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="preSetup" time="8.180"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_73_To_Validate_the_presence_of_placeholder_in_the_Create_password_Fields" time="1.588"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_60_To_Validate_the_next_function_without_entering_a_value_in_Enter_password_and_ReEnter_password" time="3.271">
    <failure message="expected [Must your 4 digit PIN.] but found [Must set your 4 digit PIN.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Must your 4 digit PIN.] but found [Must set your 4 digit PIN.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities.TC_60_To_Validate_the_next_function_without_entering_a_value_in_Enter_password_and_ReEnter_password(CreatePasswrod_Screen_And_its_Functionalities.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_60_To_Validate_the_next_function_without_entering_a_value_in_Enter_password_and_ReEnter_password -->
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_57_To_Validate_with_Valid_value_in_enter_password_field_and_Invalid_value_in_ReEnter_password_field" time="25.219"/>
  <testcase classname="Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities" name="TC_58_To_Validate_with_Valid_value_in_both_enter_password_field_and_in_ReEnter_password_field" time="30.556"/>
</testsuite> <!-- Bchat.TestScenarios.CreatePasswrod_Screen_And_its_Functionalities -->
